# Generated by Django 4.2.1 on 2023-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('compressed_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Uploads',
                'db_table': 'Upload',
                'ordering': ['-uploaded_on'],
                'managed': True,
            },
        ),
    ]
