# Generated by Django 4.2.1 on 2023-05-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_uploadmodel_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='compressed_on',
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='sent_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='video',
            field=models.ImageField(upload_to='images'),
        ),
    ]
