# Generated by Django 4.2.1 on 2023-05-20 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_uploadmodel_compressed_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='video',
            new_name='real_image',
        ),
    ]
