# Generated by Django 4.2.1 on 2023-05-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_video_uploadmodel_real_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='compressed_image',
            field=models.ImageField(blank=True, upload_to='compressed'),
        ),
    ]
