# Generated by Django 4.2.1 on 2023-05-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_uploadmodel_compressed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='compressed_image',
            field=models.CharField(blank=True, max_length=9000),
        ),
    ]
