# Generated by Django 4.2.1 on 2023-05-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_uploadmodel_compressed_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='compressed_image',
            new_name='compressed_image_path',
        ),
    ]
